### ISSUE TITLE
 libzstd-seek can't handle large amount of files/ a large file size?

### ISSUE THREAD

**Issue by codecnotsupported** [martinellimarco/libzstd-seek#3]
I've a 45GB file compressed with t2sz to ~10 GB. Tar lists the files fine.
I ran the example `tar-zst-list` against it and then it stops at 
`data182478.dat - ftell: 1121145480`
`Error while seeking`
log2(1121145480) = 30.0623263486 bits?
Very rough guess, but, maybe it's a integer overflow & need to convert a int (un)signed 32bit int value to a unsigned 64bit int?
P.S.
When you fix this issue can you also update `indexed_zstd` to include this fix?

**Comment by codecnotsupported** [comment]
Maybe something to do with.
https://github.com/martinellimarco/libzstd-seek/blob/428f5b11b1e20e5a865d6aa83690f85fe6d88a5f/zstd-seek.h#L54-L56

**Comment by codecnotsupported** [comment]
Found it.
https://github.com/martinellimarco/libzstd-seek/blob/f52cedc874cafac60ff3c5ecdd3b6eadd167ec8a/zstd-seek.c#L158-L159
Changing it to `uint64_t` fixes it.
I would still suggest you review other parts of the code.

**Comment by martinellimarco** [comment]
Thank you for reporting this. I will carefully review the code and make sure to make all the required changes to support larger archives. Expect a new release soon of both this and indexed_zstd.

**Comment by martinellimarco** [comment]
I see the problem is related to the jump table decoded from the [seekable format](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md). This was a later addition to the library and it's less tested than the rest.
cOffset and dOffset should have been defined as size_t and not uint32_t from the beginning.

**Comment by mxmlnkn** [comment]
Note that size_t can be 32-bit on 32-bit platforms. It can even be a signed integer on Windows. To be truly portable, uint64_t should do the trick.

**Comment by martinellimarco** [comment]
Yes, I'm aware of that but zstd too always refer to size_t in the [manual](https://facebook.github.io/zstd/zstd_manual.html) and the API and that's why I matched the type in my code.
If I change this to uint64_t I would have to change other size_t to uint64_t to be consistent but then what happens on 32bit platforms where we use uint64_t and zstd uses size_t that is 32bit?

**Comment by mxmlnkn** [comment]
:/ Ah ok. If it has been encoded in the zstd API, then it is too late to change it. size_t is the correct choice then, I would say.

**Comment by martinellimarco** [comment]
I spent the last hour thinking about it and trying to make it uint64_t but at the end I have to pass this value to zstd which expect a size_t so I don't see a way around it. I wonder how zstd behave on 32bit platforms, I will setup a virtual machine and test it a bit.

While reviewing the code I also spotted a problem if there are more than 2^32 frames in the file, which is unlikely (and not supported by the official seekable format, but t2sz can technically handle it). I bumped the limit to 2^64 which is absurdly high.

The code is in the branch named fix3. I will stress test the library before releasing it.
