### ISSUE TITLE
Have you looked into the feasability of seeking to blocks, rather than frames?

### ISSUE THREAD

**Issue by vasi** [martinellimarco/libzstd-seek#6]
[I](https://github.com/vasi/lzopfs?tab=readme-ov-file#gzip) and [others](https://github.com/pauldmccarthy/indexed_gzip) have done this sort of thing for gzip, by checkpointing the decompressor state. But it's not yet clear to me whether the zstd API makes this possible, so I was wondering if you'd investigated. The "Buffer-less streaming decompression" docs sound useful, but a bit incomplete.

Thanks!

**Comment by mxmlnkn** [comment]
Hi,

I am not the maintainer of this project, but I am maintaining [indexed_bzip2](https://github.com/mxmlnkn/indexed_bzip2), which [indexed_zstd](https://github.com/martinellimarco/indexed_zstd/) used as a skeleton, and [rapidgzip](https://github.com/mxmlnkn/rapidgzip), which is basically indexed_gzip, but with thread-parallel support and some additional features such as window compression and window sparsity detection to reduce the window sizes. Rapidgzip also supports bzip2, raw deflate, and zlib, and I intend to use it for LZ4 seeking and parallel decompression next and hope to maybe add Zstandard in the future. Note that there is also [gztool](https://github.com/circulosmeos/gztool), which also can seek in gzips. I did not know that lzopfs supports random access to gzip.

The pointer to [Buffer-less streaming decompression](https://facebook.github.io/zstd/zstd_manual.html#Chapter22) is helpful. The last time, I checked, I tried to read the zstandard format itself, which was quite a lot more complicated than gzip in my opinion. The problematic part is also mentioned in the linked chapter:

> For extended interoperability, it is recommended to support `windowSize` of at least 8 MB.

Gzip limits this to 32 KiB and Zstandard only **recommends** 8 MiB, but in general, it is basically unlimited, and even worse, specifying the window size seems to be [optional](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#window_descriptor)! This makes Zstandard even less suitable for random access than gzip. In my opinion, they really should make the multi-frame format the default compression mode, else I cannot full-heartedly recommend it...

> When `Single_Segment_flag` is set, `Window_Descriptor` is not present.
In this case, `Window_Size` is `Frame_Content_Size`,
which can be any value from 0 to 2^64-1 bytes (16 ExaBytes).

> minimum `Window_Size` is 1 KB.
> The maximum `Window_Size` is `(1<<41) + 7*(1<<38)` bytes, which is 3.75 TB.

> For improved interoperability,
it's recommended for decoders to support `Window_Size` of up to 8 MB,
and it's recommended for encoders to not generate frame requiring `Window_Size` larger than 8 MB.

Even that 8 MiB limit would require a 256x larger index than for gzip or inversely proportional fewer seek points. Note that LZ4 has a window size of 64 KiB.

My hope for LZ4 and Zstandard is the almost finished sparse window detection in rapidgzip. The idea here is to only actually store the data in the window that is referenced in the subsequent data stream. In my experiments, only ~10% of the window are referenced, i.e., this would compress the window by 90%. But, when the window is already compressed, then the sparse window reduction effectively only shaves off ~50% in most of my tested use cases because it often shaves off redundant parts that did increase the compressibility.

The big problem here would be that there is no API for Zstandard or LZ4 for this, as far as I know. I would have to write a custom decoder, which based on the RFC seems much more complicated than for gzip, or fork a custom decoder. This custom decoder would then collect all LZ references to detect which parts of the window are used and which can be zeroed out. The sparsity should limit the index seek point size to the amount of the decompressed size between seek points in the worst case, which hopefully is very rare.

Looking at the manual of zstd, there is another window size limit that is frequently mentioned: 2^27 = 128 MiB:

> `--long[=#]`: enables long distance matching with # windowLog, if not # is not present it defaults to 27.

> Note: If windowLog is set to larger than 27, --long=windowLog or --memory=windowSize needs to be passed to the decompressor.

I can't quite find out the default window size in the source code or the manual... A simple trial and error with silesia.tar.zst and `head -c $(( 4 * 1024 * 1024 )) /dev/urandom | base64` and `zstd -l -v` shows a window size of 2 MiB.

**Comment by vasi** [comment]
Hi Maximilian, great to meet you! Always been impressed by your work, glad I could also contribute to this space with lzopfs and pixz.

> Zstandard only recommends 8 MiB, but in general, it is basically unlimited, and even worse, specifying the window size seems to be [optional](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#window_descriptor)!

Oh no, that's really painful. I agree that basically makes random access to arbitrary zstd files untenable. Your work on sparse windows is fascinating, but you're right that it may not help enough.

> In my opinion, they really should make the multi-frame format the default compression mode, else I cannot full-heartedly recommend it...

I agree wholeheartedly! I've [argued before](https://github.com/facebook/zstd/issues/395#issuecomment-974796390) that the way forward is to ship tooling for multi-frame zstd as widely as possible. Maybe I should try to get t2sz into Debian?

Another option may be advocating for `--rsyncable` to be the default, or at least more widely used. That mode should create enough "independent" blocks for us to use for random access. Unfortunately, I'm not seeing any way in the zstd API to tell that a block is truly independent of the previous window. The only ways to find out are to try decompressing it with no window and see if it fails; or attempt to parse it out and see if there are back-references.

I'm also rather confused by [this claim](https://github.com/facebook/zstd/issues/1155#issuecomment-890350338) that "--rsyncable creates inter-related blocks". Surely zstd must be discarding the lookback window at synchronization points, or else changes in one block would affect subsequent blocks, losing rsyncability, right?

**Comment by mxmlnkn** [comment]
> Hi Maximilian, great to meet you! Always been impressed by your work, glad I could also contribute to this space with lzopfs and pixz.

Hi Dave, I can only return the thanks. I was using pixz long before I started my work on ratarmount, for which I recommend pixz when xz is desired for compression, and its backends. Lately, I have also been looking into squashfuse as an alternative for large archives with many small files, which I was surprised to see was also written by you.

> I'm also rather confused by [this claim](https://github.com/facebook/zstd/issues/1155#issuecomment-890350338) that "--rsyncable creates inter-related blocks". Surely zstd must be discarding the lookback window at synchronization points, or else changes in one block would affect subsequent blocks, losing rsyncability, right?

Actually, no, I think it is an orthogonal feature. For rsyncability, it suffices that the compressed data stream remains unchanged after some distance from the change in the uncompressed stream. A change in the uncompressed stream will definitely also change the compressed block it appears in. The next block after it may also be affected because the back-references may change. **However**, the block after the next one will not change because the uncompressed data of the block before it also is unchanged. This way, changes in the compressed stream can be locally contained even with full block inter-dependency. It basically looks like this:

```
----+-----+----+---+----
  A | B'' | C' | D | E
----+-----+----+---+----
       ^     ^   ^
       |     |   |
       |     |  No change in the uncompressed or compressed block data.
       |    Unchanged uncompressed block, 
       |    but changed compressed block because
       |    back-references to B'' changed.
   Changed introduced in uncompressed block
   also changes the compressed block.
```

The only thing that that `--rsyncable` really seems to have to do is splitting the blocks based on the rolling hash.

> I agree wholeheartedly! I've [argued before](https://github.com/facebook/zstd/issues/395#issuecomment-974796390) that the way forward is to ship tooling for multi-frame zstd as widely as possible. Maybe I should try to get t2sz into Debian?

Ah yes, I remember that issue. I have upvoted it many years ago. Too bad nothing came from it. Pushing t2sz into Debian probably would be helpful to proliferate more suitably compressed archives. It's definitely better than requiring users to build from source or installing it via yet another package manager such as snap. I never pushed for a package to be included into Debian, so I don't really know how it works, though I plan to do it for rapidgzip sometime in the future. This is more of a question for @martinellimarco anyway.

**Comment by martinellimarco** [comment]
Hi everyone,

At the moment, I don't have the time to delve into the technical details needed for this type of modification to the libzstd-seek library due to my current workload on different activities. However, pull requests are welcome.

If you're interested in publishing t2sz on Debian, we can discuss it in the appropriate repository. I don't have experience in publishing Debian packages, but I have no objections as long as we publish a revised version of t2sz with more features and testing, including the requested feature for reading from stdin.

For now, I'm closing this issue.
